### ISSUE TITLE
Netlify url link

### ISSUE THREAD

**Issue by morswin22** [krylowicz/Spacer#10]
Try to change the url of the live preview on netlify to something more space related or just "spacer" if avaible

**Comment by krylowicz** [comment]
Custom urls aren’t free

**Comment by morswin22** [comment]
Sure there are, just change the subdomain name

1. First, open settings:
![image](https://user-images.githubusercontent.com/23561091/54790205-a19e6200-4c35-11e9-8715-db98f1a2f755.png)

1. Then just change site name
![image](https://user-images.githubusercontent.com/23561091/54790259-c98dc580-4c35-11e9-93ca-4162bbd96c08.png)

This is my example of this being free: https://hexapawn.netlify.com/
